export const USER_ACTIONS = {
    GET_USER: 'GET_USER',
    UPDATE_USER: 'UPDATE_USER',
    SAVE_USER_CHANGES: 'SAVE_USER_CHANGES',
    UPDATE_PROFILE_IMAGE: 'UPDATE_PROFILE_IMAGE',
    RESET_USER_IMAGE: 'RESET_USER_IMAGE',
    GET_MY_ORDERS: 'GET_MY_ORDERS',
    GET_ORDER_LINES: 'GET_ORDER_LINES'
}

export const USER_MUTATIONS = {
    SET_USER: 'SET_USER',
    SET_PROFILE_CHANGED: 'SET_PROFILE_CHANGED',
    SET_MY_ORDERS: 'SET_MY_ORDERS',
    INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
}
