
const myOrderConstantData = {
    defaultActivity: {
        total: [
            {
                label: 'Total Orders',
                value: 6,
            },
        ],
        pending: [
            {
                label: 'Pending Orders',
                value: 2,
            },
        ],
        inProgress: [
            {
                label: 'In Progress Orders',
                value: 1,
            },
        ],
        completed: [
            {
                label: 'Completed Orders',
                value: 3,
            },
        ],
    },
    cartItem: [
        {
            index: 0,
            image: 'mobile.png',
            title: '3D Implant Planning',
            amount: true,
            price: '$400.00',
            oldprice: '$655.00',
            seeMore: true,
            detail: 'See Details',
            showBtn: 'false',
        },
        {
            index: 1,
            image: 'mobile.png',
            title: 'Surgical guide for single implant',
            amount: true,
            price: '$400.00',
            oldprice: '$655.00',
            seeMore: true,
            detail: 'See Details',
            showBtn: 'false',
        },
        {
            index: 2,
            image: 'mobile.png',
            title: 'Surgical guide for single implant',
            amount: true,
            price: '$400.00',
            oldprice: '$655.00',
            seeMore: true,
            detail: 'See Details',
            showBtn: 'false',
        },
        {
            index: 3,
            image: 'mobile.png',
            title: 'Surgical guide for single implant',
            amount: true,
            price: '$400.00',
            oldprice: '$655.00',
            seeMore: true,
            detail: 'See Details',
            showBtn: 'false',
        },
    ],
    tableContent: [
        {
            index: 1,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'In Progress',
            method: 'Bank Transfer',
            more: ['Change Payment Method', 'Report a problem'],
            pending: true,
        },
        {
            index: 2,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'Completed',
            method: 'Bank Transfer',
            more: ['Change Payment Method', 'Report a problem'],
            complete: true,
        },
        {
            index: 3,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'Completed',
            method: 'Credit or Debit Cards',
            more: ['Change Payment Method', 'Report a problem'],
            complete: true,
        },
        {
            index: 4,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'Completed',
            method: 'Pay with Paypal',
            more: ['Change Payment Method', 'Report a problem'],
            complete: true,
        },
        {
            index: 5,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'In Progress',
            method: 'Credit or Debit Cards',
            more: ['Change Payment Method', 'Report a problem'],
            fail: true,
        },
        {
            index: 6,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'In Progress',
            method: 'Credit or Debit Cards',
            more: ['Change Payment Method', 'Report a problem'],
            cancel: true,
        },
        {
            index: 7,
            id: '#123456',
            date: '19/04/2021',
            amount: '$1,295.00',
            status: 'In Progress',
            method: 'Bank Transfer',
            more: ['Change Payment Method', 'Report a problem'],
            refund: true,
        },
    ]
}

export default myOrderConstantData