export const COMMON_ACTIONS = {
    SHOW_SPLASH_SCREEN: 'SHOW_SPLASH_SCREEN',
    HIDE_SPLASH_SCREEN: 'HIDE_SPLASH_SCREEN',
    CLOSE_OVERLAY: 'CLOSE_OVERLAY',
}

export const COMMON_MUTATIONS = {
    SET_LOADING: 'SET_LOADING',
    SET_UPLOAD_PROGRESS: 'SET_UPLOAD_PROGRESS',
    SET_OVERLAY: 'SET_OVERLAY',
    CLOSE_OVERLAY: 'CLOSE_OVERLAY',
    SET_SUCCESS: 'SET_SUCCESS',
    SET_ERROR: 'SET_ERROR',
    SPLASH_SCREEN_START:'SPLASH_SCREEN_START',
    SPLASH_SCREEN_END:'SPLASH_SCREEN_END',
}