export const CHECKOUT = {
    POST_CHECKOUT: 'postCheckout',
    GET_SHIPPING_METHODS: 'getShippingMethods',
    GET_COUNTRIES: 'getCountries',
    UPDATE_SHIPING_ADDRESS: 'updateShppingAddress',
    UPDATE_BILLING_ADDRESS: 'updateBillingAddress',
    PLACE_ORDER: "placeOrder",
    GET_ORDER_LINES: "getOrderLines",
    SET_AI_SELECTED_PRICE_PLAN: "setAiSelectedPricePlan",
    FULFILL_PAYMENT_INTENT: "fulfillPaymentIntent",
    GET_COUNTRY_SHIPING_COST: "getCountryShippingCost"
}

export const CHECKOUT_ACTIONS = {
    GET_COUNTRIES: 'GET_COUNTRIES',
    GET_SHIPPING_METHODS: 'GET_SHIPPING_METHODS',
    PLACE_ORDER: "PLACE_ORDER",
    LOAD_DIGITAL_ORDER_DATA: "LOAD_DIGITAL_ORDER_DATA",
    FULFILL_PAYMENT_INTENT: "FULFILL_PAYMENT_INTENT"
}

export const CHECKOUT_MUTATIONS = {
    SET_COUNTRIES: 'SET_COUNTRIES',
    SET_SHIPING_ADDRESS:  'SET_SHIPING_ADDRESS',
    SET_BILLING_ADDRESS:  'SET_BILLING_ADDRESS',
    SET_SHIPPING_METHODS: 'SET_SHIPPING_METHODS',
    SET_ORDER_DATA: "SET_ORDER_DATA",
    SET_ORDER_LINE: "SET_ORDER_LINE",
    SET_DIGITAL_ORDER_DATA: "SET_DIGITAL_ORDER_DATA",
    FULFILL_PAYMENT_INTENT: "FULFILL_PAYMENT_INTENT",
}