export const SERVICE = {
    PATIENTS: 'getPatients',
    ADD_PATIENT: "addPatient",
    ADD_SERVICE: "addService",
    UPDATE_LOCAL_SERVICE: "updateLocalService",
    UPDATE_UPLOADED_FILES: "updateUploadedFiles",
    REMOVE_UPLOADED_FILES: "removeUploadedFile",
    UPDATE_IMPLANT: "updateImplant",

    GET_SERVICES: 'getServices',
    GET_SERVICE_DETAIL: 'getServiceDetail',
    GET_ACTIVE_ORDER_LINES: 'getActiveOrderLines',
    GET_PATINET_AI_SERVICE: 'getPatientAiService',

}

export const SERVICE_MUTATIONS = {
    SET_PATIENTS: "SET_PATIENTS",
    SET_SERVICES: "SET_SERVICES",
    SET_ACTIVE_ORDER_LINES: "SET_ACTIVE_ORDER_LINES",
    SET_ACTIVE_ORDER_LINE: "SET_ACTIVE_ORDER_LINE",
    SET_PATIENT_AI_SERVICES: "SET_PATIENT_AI_SERVICES",
    SET_SERVICE_DETAIL: "SET_SERVICE_DETAIL",
    SET_FILTER: "SET_FILTER",
}

export const SERVICE_ACTIONS = {
    GET_PATIENTS: "GET_PATIENTS",
    SEARCH_PATIENTS: "SEARCH_PATIENTS",
    ADD_PATIENTS: "ADD_PATIENTS",
    GET_SERVICES: "GET_SERVICES",
    FILTER_SERVICES: "FILTER_SERVICES",
    GET_ACTIVE_ORDER_LINES: "GET_ACTIVE_ORDER_LINES",
    GET_ACTIVE_ORDER_LINE: "GET_ACTIVE_ORDER_LINE",
    GET_PATIENT_AI_SERVICES: "GET_PATIENT_AI_SERVICES",
    GET_SERVICE_DETAIL: "GET_SERVICE_DETAIL",
    ADD_SERVICE: "ADD_SERVICE",
    UPDATE_SERVICE: "UPDATE_SERVICE",
    PUSH_TEMP_FILE: "PUSH_TEMP_FILE",
    ADD_SERVICE_FILE: "ADD_SERVICE_FILE",
    SUBMIT_PHASE_FIELDS: "SUBMIT_PHASE_FIELDS",
    UPDATE_PHASE_STATUS: "UPDATE_PHASE_STATUS",
    GET_FILE_SIGNTURE: "GET_FILE_SIGNTURE",
    CLOSE_SERVICE: "CLOSE_SERVICE",
}
