/*export const CATALOGUE = {
    GET_CART: "getCart",
    CART_LINES: "cartLines",
    ADD_CART: 'addCart',
    REMOVE_CART: 'removeCart',
    REPLACE_CART_ITEM: 'replaceCartItem',
    UPDATE_CART_QTY: 'updateCartQty',
    UPDATE_CART_LINE_ATTR: 'updateCartLineAttr'
}*/

export const CART_ACTIONS = {
    GET_CART: "GET_CART",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REPLACE_CART_ITEM: "REPLACE_CART_ITEM",
    UPDTAE_CART_LINE_ATTRIBUTE: "UPDTAE_CART_LINE_ATTRIBUTE",
    ADD_LINE_ATTRIBUTE: "ADD_LINE_ATTRIBUTE",
    UPDTAE_CART_LINE_QUANTITY: "UPDTAE_CART_LINE_QUANTITY",
    ADD_COUPON_TO_CART: "ADD_COUPON_TO_CART",
    CLEAR_COUPON_DATA: "CLEAR_COUPON_DATA",
}

export const CART_MUTATIONS = {
    SET_CART: "SET_CART",
    SET_CART_LINES: "SET_CART_LINES",
    SET_COUPON: "SET_COUPON",
}
