export const UPDATE_PANORAMA_SERVICE = "UPDATE_PANORAMA_SERVICE";
export const ADD_PANORAMA_SERVICE_FILE = "ADD_PANORAMA_SERVICE_FILE";
export const UPDATE_PANORAMA_SERVICE_FILE = "UPDATE_PANORAMA_SERVICE_FILE";
export const DELETE_PANORAMA_SERVICE_FILE = "DELETE_PANORAMA_SERVICE_FILE";
export const START_PANORAMA_ANALYSIS = "START_PANORAMA_ANALYSIS";
export const START_LOCAL_AI_ANALYSIS = "START_LOCAL_AI_ANALYSIS";

